<?php

use Illuminate\Database\Seeder;

class news extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('news')->insert([
            ['title'=>'Làm thế nào để ngăn ngừa virus','content'=>'Nghe có vẻ lạ lẫm, nhưng thực chất người dùng có thể thấy chúng nhan nhản trên các trang mạng chuyên tải về hoặc các trang cung cấp tài nguyên miễn phí. Như hình ảnh dưới đây, nếu không nhìn kỹ, rất có thể người dùng sẽ vô tình nhấp vào nút Download giả mạo mà không hay biết. Kết quả là người dùng sẽ tải nhầm một tập tin hoặc trình cài đặt độc hại – đa phần là mã độc hoặc phần mềm quảng cáo, thanh công cụ trên trình duyệt…Rõ ràng đây là một cách lừa đảo hết sức tinh vi vì đánh vào tâm lý người sử dụng khi muốn nhanh chóng tải một tập tin hay tài nguyên nào đó về máy tính của mình để sử dụng. Thường thì các nút download này còn nổi bật hơn cả nút download thật, nên nhanh chóng thu hút sự chú ý của người dùng.','id_category'=>1,'id_user'=>1,'link_image'=>'fontend/assets/img/news1.jpg','created_at'=>'2020-05-05 16:22:19'],
            ['title'=>'IPhone 12 có thể ra mắt muộn vào tháng 10 tới','content'=>'Theo trang iPhonehacks, nguồn tin Jon Prosser mới tiết lộ rằng, Apple sẽ dời toàn bộ sự kiện công bố iPhone 12 sang tháng 10, thay vì tháng 9 như các năm trước.Các tin đồn cho đến thời điểm này đều khẳng định Apple sẽ ra mắt 2 biến thể bao gồm iPhone 12 vào tháng 9 và phát hành iPhone 12 Pro vài tuần sau đó vào tháng 10.Apple cũng thực hiện cách thức tương tự với iPhone X ra mắt năm 2017 với việc được giới thiệu vào tháng 9 cùng iPhone 8 và iPhone 8 Plus nhưng phải sang tháng 10 thiết bị mới được phát hành.Việc phát triển dòng iPhone 12 bị chậm tiến độ do dịch bệnh bùng phát. Bất chấp các nguyên nhân gây chậm trễ, các nhà phân tích và chuỗi cung ứng dự kiến Táo khuyết vẫn sẽ ra mắt iPhone 12 vào tháng 9. Mặc dù đã có nhiều báo cáo mâu thuẫn về việc iPhone 12 ra mắt trong năm nay.','id_category'=>2,'id_user'=>1,'link_image'=>'fontend/assets/img/news2.jpg','created_at'=>'2020-05-05 16:22:19'],
            ['title'=>'IPhone 13 có thể ra mắt muộn vào tháng 10 tới','content'=>'Theo trang iPhonehacks, nguồn tin Jon Prosser mới tiết lộ rằng, Apple sẽ dời toàn bộ sự kiện công bố iPhone 12 sang tháng 10, thay vì tháng 9 như các năm trước.Các tin đồn cho đến thời điểm này đều khẳng định Apple sẽ ra mắt 2 biến thể bao gồm iPhone 12 vào tháng 9 và phát hành iPhone 12 Pro vài tuần sau đó vào tháng 10.Apple cũng thực hiện cách thức tương tự với iPhone X ra mắt năm 2017 với việc được giới thiệu vào tháng 9 cùng iPhone 8 và iPhone 8 Plus nhưng phải sang tháng 10 thiết bị mới được phát hành.Việc phát triển dòng iPhone 12 bị chậm tiến độ do dịch bệnh bùng phát. Bất chấp các nguyên nhân gây chậm trễ, các nhà phân tích và chuỗi cung ứng dự kiến Táo khuyết vẫn sẽ ra mắt iPhone 12 vào tháng 9. Mặc dù đã có nhiều báo cáo mâu thuẫn về việc iPhone 12 ra mắt trong năm nay.','id_category'=>2,'id_user'=>1,'link_image'=>'fontend/assets/img/news3.jpg','created_at'=>'2020-05-05 16:22:19'],
            ['title'=>'IPhone 14 có thể ra mắt muộn vào tháng 10 tới','content'=>'Theo trang iPhonehacks, nguồn tin Jon Prosser mới tiết lộ rằng, Apple sẽ dời toàn bộ sự kiện công bố iPhone 12 sang tháng 10, thay vì tháng 9 như các năm trước.Các tin đồn cho đến thời điểm này đều khẳng định Apple sẽ ra mắt 2 biến thể bao gồm iPhone 12 vào tháng 9 và phát hành iPhone 12 Pro vài tuần sau đó vào tháng 10.Apple cũng thực hiện cách thức tương tự với iPhone X ra mắt năm 2017 với việc được giới thiệu vào tháng 9 cùng iPhone 8 và iPhone 8 Plus nhưng phải sang tháng 10 thiết bị mới được phát hành.Việc phát triển dòng iPhone 12 bị chậm tiến độ do dịch bệnh bùng phát. Bất chấp các nguyên nhân gây chậm trễ, các nhà phân tích và chuỗi cung ứng dự kiến Táo khuyết vẫn sẽ ra mắt iPhone 12 vào tháng 9. Mặc dù đã có nhiều báo cáo mâu thuẫn về việc iPhone 12 ra mắt trong năm nay.','id_category'=>2,'id_user'=>1,'link_image'=>'fontend/assets/img/news4.jpg','created_at'=>'2020-05-05 16:22:19'],
            ['title'=>'IPhone 15 có thể ra mắt muộn vào tháng 10 tới','content'=>'Theo trang iPhonehacks, nguồn tin Jon Prosser mới tiết lộ rằng, Apple sẽ dời toàn bộ sự kiện công bố iPhone 12 sang tháng 10, thay vì tháng 9 như các năm trước.Các tin đồn cho đến thời điểm này đều khẳng định Apple sẽ ra mắt 2 biến thể bao gồm iPhone 12 vào tháng 9 và phát hành iPhone 12 Pro vài tuần sau đó vào tháng 10.Apple cũng thực hiện cách thức tương tự với iPhone X ra mắt năm 2017 với việc được giới thiệu vào tháng 9 cùng iPhone 8 và iPhone 8 Plus nhưng phải sang tháng 10 thiết bị mới được phát hành.Việc phát triển dòng iPhone 12 bị chậm tiến độ do dịch bệnh bùng phát. Bất chấp các nguyên nhân gây chậm trễ, các nhà phân tích và chuỗi cung ứng dự kiến Táo khuyết vẫn sẽ ra mắt iPhone 12 vào tháng 9. Mặc dù đã có nhiều báo cáo mâu thuẫn về việc iPhone 12 ra mắt trong năm nay.','id_category'=>2,'id_user'=>1,'link_image'=>'fontend/assets/img/news5.jpg','created_at'=>'2020-05-05 16:22:19'],
            ['title'=>'IPhone 16 có thể ra mắt muộn vào tháng 10 tới','content'=>'Theo trang iPhonehacks, nguồn tin Jon Prosser mới tiết lộ rằng, Apple sẽ dời toàn bộ sự kiện công bố iPhone 12 sang tháng 10, thay vì tháng 9 như các năm trước.Các tin đồn cho đến thời điểm này đều khẳng định Apple sẽ ra mắt 2 biến thể bao gồm iPhone 12 vào tháng 9 và phát hành iPhone 12 Pro vài tuần sau đó vào tháng 10.Apple cũng thực hiện cách thức tương tự với iPhone X ra mắt năm 2017 với việc được giới thiệu vào tháng 9 cùng iPhone 8 và iPhone 8 Plus nhưng phải sang tháng 10 thiết bị mới được phát hành.Việc phát triển dòng iPhone 12 bị chậm tiến độ do dịch bệnh bùng phát. Bất chấp các nguyên nhân gây chậm trễ, các nhà phân tích và chuỗi cung ứng dự kiến Táo khuyết vẫn sẽ ra mắt iPhone 12 vào tháng 9. Mặc dù đã có nhiều báo cáo mâu thuẫn về việc iPhone 12 ra mắt trong năm nay.','id_category'=>2,'id_user'=>1,'link_image'=>'fontend/assets/img/news6.jpg','created_at'=>'2020-05-05 16:22:19']
        ]);
    }
}
